language: java
addons:
  firefox: "latest"
script: CI=1 MOZ_HEADLESS=1 ./gradlew clean npm_install npm_test test
cache:
  directories:
  - $HOME/.gradle/caches
  - frontend/node_modules
install: true
env:
  global:
    secure: mLwTEcPuSjzmKhjE6/7spqy0UOXThELdNtf/LAw3Mf1nKUD8KWnRsSd8EBR8FBR3Wgsaxh90vik379642gox8t47GHQEpm1EhD7dsbJSzuiR04y3ou66sb+rcSuewM6W2U8+yJiTaKIk/rkvU05dJJrJwRSQ9r+l5adauwUK1sFSJOVGDQyjUgmLsV4Xstddk4VywCBYd3cq9s6pcmg1ysyrqE9/B5G+hdtF22n+fz8Usm5aIdGS4/sUPbn8ApzFz202uU1Is0YZfJLR9sM3uVUPDuYJWpxqoU8dkv1XhguqbCy7h5hSqBPEySDkzKZhKnvF5ucVMQpDO7ZHQjgcnVQ/MxpBGJvulfwpBYaBey8vK+3S6VvUv9qQTl25LDHVg4HniapJjrXoqVP3HdI9jyBEJvDsEzs1Z4x52u5UH4mZRX56wbwqSGSim8lQeciu9UjVLPVDcflhWA6X4mIckcCZyJFfUshErDPYDu69aNQ846DPIYH/s5DGYu0XyRTjGSMkeCBD6Cx/AsFbJXvY31rXMic50Y32L/UP5y/zAdKGTTwW5mDqbWeUh539tUPcxGmOY03aTxYf2GaR8InEHLVMndLvcP/bvFtNF4UD+erRfkIRq5MICwnJ8bOpUfkIL8oxi6ipukNrUIIinfbcm8sABMuWa/1flFptp7DwjHk=
